# Generated by Django 4.2.6 on 2024-03-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_gasto', models.CharField(blank=True, choices=[('leche', 'Leche'), ('transporte', 'Transporte'), ('empleados', 'Empleados'), ('transporte_queso', 'Transporte Queso'), ('flete_queso', 'Flete Queso'), ('cuajador_mirolindo', 'Cuajador Mirolindo'), ('sal', 'Sal'), ('varios', 'Varios'), ('jabon', 'Jabón'), ('cuajo', 'Cuajo'), ('energia', 'Energía'), ('bolsas', 'Bolsas'), ('cloro', 'Cloro')], null=True)),
                ('descripcion', models.CharField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('data_register', models.DateTimeField(auto_now_add=True)),
                ('day', models.DateField(blank=True, default=None, null=True)),
                ('producion_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.producionday')),
            ],
        ),
    ]
