# Generated by Django 4.2.6 on 2024-04-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_remove_gastos_producion_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='gastos',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
