# Generated by Django 4.2.6 on 2024-03-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProducionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(blank=True, default=None, null=True)),
                ('data_register', models.DateTimeField(auto_now_add=True)),
                ('name_producction', models.CharField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('data_register', 'name_producction')},
            },
        ),
        migrations.CreateModel(
            name='ProductionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_register', models.DateTimeField(auto_now_add=True)),
                ('producto', models.CharField(blank=True, null=True)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('producionday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.producionday')),
            ],
        ),
    ]
