# Generated by Django 4.2.6 on 2024-01-21 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("production", "0002_remove_producionday_producrion_producto_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producionday",
            name="register_day",
        ),
        migrations.AddField(
            model_name="producionday",
            name="day",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
