# Generated by Django 4.2.6 on 2024-03-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('comprador', models.CharField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, choices=[('Pagado', 'pagado'), ('Debe', 'debe')], null=True)),
                ('fecha_venta_incio', models.DateField(blank=True, null=True)),
                ('fecha_venta_final', models.DateField(blank=True, null=True)),
                ('data_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
