# Generated by Django 4.2.6 on 2024-04-20 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_inicio', models.DateField(blank=True, default=None, null=True)),
                ('dia_final', models.DateField(blank=True, default=None, null=True)),
                ('data_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='ganaciasflete',
            old_name='name_producction',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='gastoscarro',
            old_name='producto',
            new_name='descripcion',
        ),
        migrations.AlterUniqueTogether(
            name='ganaciasflete',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='gastoscarro',
            name='producionday',
        ),
        migrations.AddField(
            model_name='ganaciasflete',
            name='cantidad',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ganaciasflete',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ganaciasflete',
            name='turbo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.turbo'),
        ),
        migrations.AddField(
            model_name='ganaciasflete',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gastoscarro',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gastoscarro',
            name='turbo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.turbo'),
        ),
        migrations.AddField(
            model_name='gastoscarro',
            name='valor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turbo',
            name='cedula',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turbo',
            name='conductor',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turbo',
            name='turbo',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ganaciasflete',
            name='flete',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.flete'),
        ),
        migrations.AddField(
            model_name='gastoscarro',
            name='flete',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='charge.flete'),
        ),
    ]
