# Generated by Django 4.2.6 on 2024-03-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liter_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeudaProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_register', models.DateTimeField(auto_now_add=True)),
                ('fecha_deuda', models.CharField(blank=True, null=True)),
                ('valor_total_deuda', models.BigIntegerField(blank=True, default=0, null=True)),
                ('provedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liter_control.provedor')),
            ],
        ),
    ]
