# Generated by Django 4.2.6 on 2024-01-14 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, null=True)),
                ('placa', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterDayTrasport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField(blank=True, null=True)),
                ('trabajo', models.BooleanField(default=True)),
                ('day', models.DateField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trasporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_register', models.DateTimeField(auto_now_add=True)),
                ('automovil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.automovil')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.empleado')),
                ('registerdaytrasport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.registerdaytrasport')),
            ],
        ),
    ]
