# Generated by Django 4.2.6 on 2024-03-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('liter_control', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trasporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.CharField(blank=True, null=True)),
                ('automovil', models.CharField(blank=True, null=True)),
                ('data_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterDayTrasporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_register', models.DateTimeField(auto_now_add=True)),
                ('value_liter_traspo', models.IntegerField(blank=True, null=True)),
                ('adelantos', models.IntegerField(default=0)),
                ('registerday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liter_control.registerday')),
                ('trasporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transportation.trasporte')),
            ],
        ),
    ]
