# Generated by Django 4.2.6 on 2024-03-17 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liter_control', '0001_initial'),
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdaytrasporte',
            name='litros_no_llegaron',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='trasporte',
            name='ruta',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='liter_control.ruta'),
        ),
    ]
