# Generated by Django 4.2.6 on 2024-01-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transportation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="automovil",
            name="color",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="automovil",
            name="estado",
            field=models.CharField(blank=True, null=True),
        ),
    ]
