# Generated by Django 4.2.6 on 2024-04-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0002_registerdaytrasporte_litros_no_llegaron_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trasporte',
            name='cedula',
            field=models.CharField(blank=True, null=True),
        ),
    ]
