# Generated by Django 4.2.6 on 2024-03-17 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterDayEmploy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('data_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True)),
                ('data_register', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_register', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(blank=True, null=True)),
                ('second_name', models.CharField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, null=True)),
                ('second_last_name', models.CharField(blank=True, null=True)),
                ('cedula', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, null=True)),
                ('total_dias', models.BigIntegerField(blank=True, null=True)),
                ('valor_del_dia', models.IntegerField(blank=True, null=True)),
                ('adelantos', models.IntegerField(blank=True, null=True)),
                ('anexos', models.IntegerField(blank=True, null=True)),
                ('valor_total', models.IntegerField(blank=True, null=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.rol')),
            ],
        ),
    ]
